### ISSUE TITLE
High memory consumption during upload

### ISSUE THREAD

**Issue by plaidshirtakos** [spinning10/JMeterSoapSampler#6]
I execute an upload test with a 70 MB pdf file on one thread, one time and get “Out of Memory” error message. 

I set set `HEAP=-Xms1g -Xmx2g` in jmeter.bat file.

**Comment by spinning10** [comment]
Hi
Can you try with set HEAP=-Xms512m -Xmx4096m?
Now it's hard to say since I don't use the plugin for some time. But I used for big files, and at that time the packer was causing OOM, when I changed to different one it resolved the situation. Huge files were being loaded according to my remaining memory.

**Comment by plaidshirtakos** [comment]
I tried it with HEAP=-Xms1g -Xmx4g too, but I have only 8 GB RAM memory.

**Comment by plaidshirtakos** [comment]
There was not enough RAM to perform action. It is OK now.
